/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package src;

/**
 *
 * @author Mark
 */
public class MyJFrame_6_full extends javax.swing.JFrame {

    
    
    int goodAnswersCount = 0;
    
    
    /**
     * Creates new form MyJFrame_6_full
     */
    public MyJFrame_6_full() {
        initComponents();
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnBegin_tab01 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jSeparator2 = new javax.swing.JSeparator();
        btnPrev_tab02 = new javax.swing.JButton();
        btnNext_tab02 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        btnPrev_tab03 = new javax.swing.JButton();
        btnNext_tab03 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        btnPrev_tab04 = new javax.swing.JButton();
        btnNext_tab04 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jRadioButton11 = new javax.swing.JRadioButton();
        jRadioButton12 = new javax.swing.JRadioButton();
        btnPrev_tab05 = new javax.swing.JButton();
        btnNext_tab05 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jRadioButton13 = new javax.swing.JRadioButton();
        jRadioButton14 = new javax.swing.JRadioButton();
        jRadioButton15 = new javax.swing.JRadioButton();
        jRadioButton16 = new javax.swing.JRadioButton();
        btnPrev_tab06 = new javax.swing.JButton();
        btnNext_tab06 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btnCheckAnsw_tab07 = new javax.swing.JButton();
        btnPrev_tab07 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabelFinal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 450));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Tab 1");

        btnBegin_tab01.setText("Begin this quiz");
        btnBegin_tab01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBegin_tab01ActionPerformed(evt);
            }
        });

        jLabel8.setText("Let's start");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(jLabel8))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(btnBegin_tab01)))
                .addContainerGap(1317, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(60, 60, 60)
                .addComponent(jLabel8)
                .addGap(28, 28, 28)
                .addComponent(btnBegin_tab01)
                .addGap(325, 325, 325))
        );

        jTabbedPane1.addTab("tab1", jPanel2);

        jLabel2.setText("Tab 2");

        jLabel9.setText("1. What type of planet is the Kepler-93 b?");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Super Earth");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Gas Giant");

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Neptunian");

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("Terrestrial");

        btnPrev_tab02.setText("Previous");
        btnPrev_tab02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrev_tab02ActionPerformed(evt);
            }
        });

        btnNext_tab02.setText("Next");
        btnNext_tab02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNext_tab02ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(jLabel9))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(60, 60, 60)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jRadioButton2)
                                            .addComponent(jRadioButton1)
                                            .addComponent(jRadioButton3)
                                            .addComponent(jRadioButton4))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 1562, Short.MAX_VALUE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(btnPrev_tab02)
                        .addGap(30, 30, 30)
                        .addComponent(btnNext_tab02)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addGap(30, 30, 30)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jRadioButton1)
                .addGap(30, 30, 30)
                .addComponent(jRadioButton2)
                .addGap(30, 30, 30)
                .addComponent(jRadioButton3)
                .addGap(30, 30, 30)
                .addComponent(jRadioButton4)
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNext_tab02)
                    .addComponent(btnPrev_tab02))
                .addContainerGap(265, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab2", jPanel3);

        jLabel3.setText("Tab 3");

        jLabel10.setText("<html>2. True or false?<br>\nThe J1407 planet has ring.</html>");

        buttonGroup2.add(jRadioButton5);
        jRadioButton5.setText("True");

        buttonGroup2.add(jRadioButton6);
        jRadioButton6.setText("False");

        btnPrev_tab03.setText("Previous");
        btnPrev_tab03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrev_tab03ActionPerformed(evt);
            }
        });

        btnNext_tab03.setText("Next");
        btnNext_tab03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNext_tab03ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel3))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton6)
                            .addComponent(jRadioButton5)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(btnPrev_tab03)
                        .addGap(30, 30, 30)
                        .addComponent(btnNext_tab03)))
                .addContainerGap(1233, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel3)
                .addGap(30, 30, 30)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jRadioButton5)
                .addGap(30, 30, 30)
                .addComponent(jRadioButton6)
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrev_tab03)
                    .addComponent(btnNext_tab03))
                .addContainerGap(365, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab3", jPanel4);

        jLabel11.setText("3. Which is the biggest planet in these list?");

        buttonGroup1.add(jRadioButton7);
        jRadioButton7.setText("The Earth");

        buttonGroup1.add(jRadioButton8);
        jRadioButton8.setText("TOI-1231 b");

        buttonGroup1.add(jRadioButton9);
        jRadioButton9.setText("Jupiter");

        buttonGroup1.add(jRadioButton10);
        jRadioButton10.setText("55 Cancri e");

        btnPrev_tab04.setText("Previous");
        btnPrev_tab04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrev_tab04ActionPerformed(evt);
            }
        });

        btnNext_tab04.setText("Next");
        btnNext_tab04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNext_tab04ActionPerformed(evt);
            }
        });

        jLabel4.setText("Tab 4");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 1608, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jLabel11))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(210, 210, 210)
                                .addComponent(btnPrev_tab04)
                                .addGap(30, 30, 30)
                                .addComponent(btnNext_tab04))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel4))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton8)
                                    .addComponent(jRadioButton7)
                                    .addComponent(jRadioButton9)
                                    .addComponent(jRadioButton10))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel4)
                .addGap(30, 30, 30)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jRadioButton7)
                .addGap(30, 30, 30)
                .addComponent(jRadioButton8)
                .addGap(30, 30, 30)
                .addComponent(jRadioButton9)
                .addGap(30, 30, 30)
                .addComponent(jRadioButton10)
                .addGap(30, 30, 30)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrev_tab04)
                    .addComponent(btnNext_tab04))
                .addContainerGap(265, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab4", jPanel5);

        jLabel5.setText("Tab 5");

        jLabel12.setText("<html>4. True or false?<br>\nWISEP J121756.91+162640.2 A is a Gas giant planet.</html>");

        buttonGroup2.add(jRadioButton11);
        jRadioButton11.setText("True");

        buttonGroup2.add(jRadioButton12);
        jRadioButton12.setText("False");

        btnPrev_tab05.setText("Previous");
        btnPrev_tab05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrev_tab05ActionPerformed(evt);
            }
        });

        btnNext_tab05.setText("Next");
        btnNext_tab05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNext_tab05ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton12)
                            .addComponent(jRadioButton11)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(btnPrev_tab05)
                        .addGap(30, 30, 30)
                        .addComponent(btnNext_tab05))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel5)))
                .addContainerGap(1233, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel5)
                .addGap(30, 30, 30)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jRadioButton11)
                .addGap(30, 30, 30)
                .addComponent(jRadioButton12)
                .addGap(30, 30, 30)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNext_tab05)
                    .addComponent(btnPrev_tab05))
                .addContainerGap(365, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab5", jPanel6);

        jLabel13.setText("Tab 6");

        jLabel19.setText("5. How many planets are in our solar system?");

        buttonGroup1.add(jRadioButton13);
        jRadioButton13.setText("6");

        buttonGroup1.add(jRadioButton14);
        jRadioButton14.setText("9");

        buttonGroup1.add(jRadioButton15);
        jRadioButton15.setText("7");

        buttonGroup1.add(jRadioButton16);
        jRadioButton16.setText("8");

        btnPrev_tab06.setText("Previous");
        btnPrev_tab06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrev_tab06ActionPerformed(evt);
            }
        });

        btnNext_tab06.setText("Next");
        btnNext_tab06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNext_tab06ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel13)
                        .addGap(30, 30, 30)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton14)
                            .addComponent(jRadioButton13)
                            .addComponent(jRadioButton15)
                            .addComponent(jRadioButton16)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jLabel19)
                                .addGap(28, 28, 28))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                .addGap(210, 210, 210)
                                .addComponent(btnPrev_tab06)
                                .addGap(30, 30, 30)))
                        .addComponent(btnNext_tab06)))
                .addContainerGap(1223, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel13)
                .addGap(30, 30, 30)
                .addComponent(jLabel19)
                .addGap(30, 30, 30)
                .addComponent(jRadioButton13)
                .addGap(30, 30, 30)
                .addComponent(jRadioButton14)
                .addGap(30, 30, 30)
                .addComponent(jRadioButton15)
                .addGap(30, 30, 30)
                .addComponent(jRadioButton16)
                .addGap(30, 30, 30)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrev_tab06)
                    .addComponent(btnNext_tab06))
                .addContainerGap(281, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab6", jPanel7);

        jLabel14.setText("Tab 7");

        jLabel15.setText("Do you want to send your answers?");

        btnCheckAnsw_tab07.setText("Check My Answers");
        btnCheckAnsw_tab07.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckAnsw_tab07ActionPerformed(evt);
            }
        });

        btnPrev_tab07.setText("Previous");
        btnPrev_tab07.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrev_tab07ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(jLabel15))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(btnPrev_tab07))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel14))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(btnCheckAnsw_tab07)))
                .addContainerGap(1234, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel14)
                .addGap(60, 60, 60)
                .addComponent(jLabel15)
                .addGap(32, 32, 32)
                .addComponent(btnCheckAnsw_tab07)
                .addGap(60, 60, 60)
                .addComponent(btnPrev_tab07)
                .addContainerGap(367, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab7", jPanel8);

        jLabel16.setText("Tab 8");

        jLabel17.setText("<html>Quiz Completed! <br>\nWell done!</html>");

        jLabel18.setText("My results:");

        jLabelFinal.setText("_/5");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(31, 31, 31)
                                .addComponent(jLabelFinal))
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel16)))
                .addContainerGap(1316, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel16)
                .addGap(26, 26, 26)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabelFinal))
                .addContainerGap(445, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab8", jPanel9);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 6, 1510, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrev_tab07ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrev_tab07ActionPerformed
        // TODO add your handling code here:
        
         jTabbedPane1.setSelectedIndex(5);
        
    }//GEN-LAST:event_btnPrev_tab07ActionPerformed

    private void btnBegin_tab01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBegin_tab01ActionPerformed
        // TODO add your handling code here:
        
         jTabbedPane1.setSelectedIndex(1);
        
    }//GEN-LAST:event_btnBegin_tab01ActionPerformed

    private void btnPrev_tab02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrev_tab02ActionPerformed
        // TODO add your handling code here:
        
        jTabbedPane1.setSelectedIndex(0);
        
    }//GEN-LAST:event_btnPrev_tab02ActionPerformed

    private void btnNext_tab02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNext_tab02ActionPerformed
        // TODO add your handling code here:
        
        jTabbedPane1.setSelectedIndex(2);
        
        
        
        
        jRadioButton1.setEnabled(false);
                
        jRadioButton2.setEnabled(false);
                        
        jRadioButton3.setEnabled(false);
                                
        jRadioButton4.setEnabled(false);
        
        
        if(jRadioButton1.isSelected() == true){
            
            goodAnswersCount++;
        }
        
        
        
        
    }//GEN-LAST:event_btnNext_tab02ActionPerformed

    private void btnPrev_tab03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrev_tab03ActionPerformed
        // TODO add your handling code here:
        
        jTabbedPane1.setSelectedIndex(1);
        
    }//GEN-LAST:event_btnPrev_tab03ActionPerformed

    private void btnNext_tab03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNext_tab03ActionPerformed
        // TODO add your handling code here:
        
        jTabbedPane1.setSelectedIndex(3);
        
        
        
        jRadioButton5.setEnabled(false);
                
        jRadioButton6.setEnabled(false);
                        
        
        
        
        if(jRadioButton5.isSelected() == true){
            
            goodAnswersCount++;
        }
        
        
        
        
        
    }//GEN-LAST:event_btnNext_tab03ActionPerformed

    private void btnPrev_tab04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrev_tab04ActionPerformed
        // TODO add your handling code here:
        
        jTabbedPane1.setSelectedIndex(2);
        
    }//GEN-LAST:event_btnPrev_tab04ActionPerformed

    private void btnNext_tab04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNext_tab04ActionPerformed
        // TODO add your handling code here:
        
        jTabbedPane1.setSelectedIndex(4);
        
        
        
        
        jRadioButton7.setEnabled(false);
                
        jRadioButton8.setEnabled(false);
                        
        jRadioButton9.setEnabled(false);
                                
        jRadioButton10.setEnabled(false);
        
        
        
        
        
        if(jRadioButton9.isSelected() == true){
            
            goodAnswersCount++;
        }
        
        
        
        
        
    }//GEN-LAST:event_btnNext_tab04ActionPerformed

    private void btnPrev_tab05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrev_tab05ActionPerformed
        // TODO add your handling code here:
        
        jTabbedPane1.setSelectedIndex(3);
        
    }//GEN-LAST:event_btnPrev_tab05ActionPerformed

    private void btnNext_tab05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNext_tab05ActionPerformed
        // TODO add your handling code here:
        
        jTabbedPane1.setSelectedIndex(5);
        
        
        
        jRadioButton11.setEnabled(false);
                
        jRadioButton12.setEnabled(false);
                        

        
        
        
        if(jRadioButton12.isSelected() == true){
            
            goodAnswersCount++;
        }
        
        
        
        
    }//GEN-LAST:event_btnNext_tab05ActionPerformed

    private void btnPrev_tab06ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrev_tab06ActionPerformed
        // TODO add your handling code here:
        
        jTabbedPane1.setSelectedIndex(4);
        
    }//GEN-LAST:event_btnPrev_tab06ActionPerformed

    private void btnNext_tab06ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNext_tab06ActionPerformed
        // TODO add your handling code here:
        
        jTabbedPane1.setSelectedIndex(6);
        
        
        
        
        jRadioButton13.setEnabled(false);
                
        jRadioButton14.setEnabled(false);
                        
        jRadioButton15.setEnabled(false);
                                
        jRadioButton16.setEnabled(false);
        
        
        
        
        if(jRadioButton16.isSelected() == true){
            
            goodAnswersCount++;
        }
        
        
        
        
        
        
        
        
        
        //isAllQuestionsAnswered = true;
        
        
        
        
        
    }//GEN-LAST:event_btnNext_tab06ActionPerformed

    private void btnCheckAnsw_tab07ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckAnsw_tab07ActionPerformed
        // TODO add your handling code here:
        
        jTabbedPane1.setSelectedIndex(7);
        
        
        // check answer
        
        int numberOfGoodAnswers = 0;
        
        boolean isSubmitted = false;
        
        
        if(!isSubmitted){
        
            
            if(jRadioButton1.isSelected() == true){
                                
                numberOfGoodAnswers++;
            
                
            }
            
            if(jRadioButton5.isSelected() == true){
                
                numberOfGoodAnswers++;
                
            
            }
            
            if(jRadioButton9.isSelected() == true){
                
                numberOfGoodAnswers++;
                
            
            }
            
            if(jRadioButton12.isSelected() == true){
                
                numberOfGoodAnswers++;
                
            
            }
            
            
            if(jRadioButton16.isSelected() == true){
                
                numberOfGoodAnswers++;
                
            
            }

            
            isSubmitted = true;
            
            //System.out.println(numberOfGoodAnswers);
            
        }
        
        
        
        //System.out.println(goodAnswersCount);
        
        
        jLabelFinal.setText(String.valueOf(goodAnswersCount) + "/5");
        
        
        
    }//GEN-LAST:event_btnCheckAnsw_tab07ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyJFrame_6_full.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyJFrame_6_full.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyJFrame_6_full.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyJFrame_6_full.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyJFrame_6_full().setVisible(true);
            }
        });
        
       
        //System.out.println("TEST");
        

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBegin_tab01;
    private javax.swing.JButton btnCheckAnsw_tab07;
    private javax.swing.JButton btnNext_tab02;
    private javax.swing.JButton btnNext_tab03;
    private javax.swing.JButton btnNext_tab04;
    private javax.swing.JButton btnNext_tab05;
    private javax.swing.JButton btnNext_tab06;
    private javax.swing.JButton btnPrev_tab02;
    private javax.swing.JButton btnPrev_tab03;
    private javax.swing.JButton btnPrev_tab04;
    private javax.swing.JButton btnPrev_tab05;
    private javax.swing.JButton btnPrev_tab06;
    private javax.swing.JButton btnPrev_tab07;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelFinal;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton13;
    private javax.swing.JRadioButton jRadioButton14;
    private javax.swing.JRadioButton jRadioButton15;
    private javax.swing.JRadioButton jRadioButton16;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
